# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93b7786ddb5585d983e2b44d200d3620b7266d4641099208607a507fc66f772ab7ed04d68c0392942b3fd24868a278641104e5d84af5f67f23b9970dbb8e8543

test:
  secret_key_base: af2f8bfc161dfd382bf05c454d608805dbe8154eafd1e497ab80e6d31f4053c60bcf10ecf70e554cb938515114979880000664ec9caf623b2d889f3ef9e285a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
